# Generated by Django 5.2.14 on 2026-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('moderator', 'Moderador'), ('coordinator', 'Coordinador'), ('member', 'Miembro')], default='member', max_length=20),
        ),
    ]
