# Generated by Django 5.2.14 on 2026-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bienvenida_inicio_pospuesto',
            field=models.BooleanField(default=False, help_text='Si el coordinador eligió «Aún no» tras completar la bienvenida.'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado_camino',
            field=models.CharField(choices=[('bienvenida', 'Periodo de bienvenida'), ('formal', 'Camino formal')], default='bienvenida', help_text='bienvenida = orientación inicial; formal = etapas, diario y ficha.', max_length=20),
        ),
    ]
