# Generated by Django 5.2.14 on 2026-09-07 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_horario_estructurado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('es_global', models.BooleanField(default=True, help_text='Si es verdadero, el evento es visible para todos los miembros.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('grupos', models.ManyToManyField(blank=True, help_text='Grupos destinatarios cuando no es global.', related_name='eventos', to='groups.grupopastoreo')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='EventoRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(choices=[('voy', 'Voy'), ('no', 'No puedo asistir')], max_length=10)),
                ('respondido_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_rsvp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Respuesta a evento',
                'verbose_name_plural': 'Respuestas a eventos',
                'ordering': ['respuesta', 'usuario__first_name', 'usuario__last_name'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'usuario'), name='unique_evento_usuario_rsvp')],
            },
        ),
    ]
