# Generated by Django 5.2.14 on 2026-09-14 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago', 'Pago'), ('evento', 'Evento'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True, help_text='False cuando se cancela (p. ej. pago ya registrado).')),
                ('clave', models.CharField(help_text='Clave de deduplicación, ej. pago:12:7 o evento:3:0', max_length=120)),
                ('referencia_tipo', models.CharField(blank=True, max_length=40)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'activa', 'leida'], name='notificatio_usuario_65a6ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'clave'), name='unique_notificacion_usuario_clave')],
            },
        ),
    ]
