# Generated by Django 5.2.14 on 2026-05-19 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPastoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('horario_reunion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contenidos', models.ManyToManyField(blank=True, related_name='grupos', to='content.contenido')),
                ('coordinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_coordinados', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(blank=True, related_name='grupos_pastoreo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de pastoreo',
                'verbose_name_plural': 'Grupos de pastoreo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EsquemaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='esquemas/')),
                ('fecha_sesion', models.DateField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas', to='groups.grupopastoreo')),
            ],
            options={
                'verbose_name': 'Esquema de grupo',
                'verbose_name_plural': 'Esquemas de grupo',
                'ordering': ['orden', '-fecha_sesion'],
            },
        ),
    ]
