# Generated by Django 5.2.14 on 2026-05-19 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaEspiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#8B7355', max_length=7)),
            ],
            options={
                'verbose_name': 'Etapa espiritual',
                'verbose_name_plural': 'Etapas espirituales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FichaPedagogica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso_general', models.PositiveIntegerField(default=0, help_text='Porcentaje 0-100')),
                ('sacramentos_recibidos', models.TextField(blank=True)),
                ('compromisos_espirituales', models.TextField(blank=True)),
                ('notas_formador', models.TextField(blank=True)),
                ('fecha_inicio_camino', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etapa_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='pedagogia.etapaespiritual')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_pedagogica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha pedagógica',
                'verbose_name_plural': 'Fichas pedagógicas',
            },
        ),
        migrations.CreateModel(
            name='AvanceEspiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='pedagogia.fichapedagogica')),
            ],
            options={
                'verbose_name': 'Avance espiritual',
                'verbose_name_plural': 'Avances espirituales',
                'ordering': ['-fecha'],
            },
        ),
    ]
