# Generated by Django 5.2.14 on 2026-06-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogia', '0003_journal_manual_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='manual_url',
            field=models.URLField(blank=True, help_text='Enlace complementario opcional'),
        ),
        migrations.AlterField(
            model_name='preguntachecklist',
            name='ayuda',
            field=models.TextField(blank=True, help_text='Orientación para la reflexión semanal'),
        ),
        migrations.AlterField(
            model_name='preguntachecklist',
            name='semana',
            field=models.PositiveIntegerField(default=1, help_text='Semana del diario'),
        ),
    ]
