# Generated by Django 5.2.14 on 2026-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogia', '0005_ficha_cuantitativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaperfil',
            name='perfil_completado',
            field=models.BooleanField(default=False, help_text='True cuando el miembro guardó al menos una vez la configuración inicial.'),
        ),
    ]
