# Generated by Django 5.2.14 on 2026-08-31 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogia', '0006_ficha_perfil_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapedagogica',
            name='avance_pospuesto_para_modulo',
            field=models.ForeignKey(blank=True, help_text='Si el coordinador eligió «Aún no», oculta el banner para esta etapa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_avance_pospuesto', to='pedagogia.modulo'),
        ),
        migrations.AddField(
            model_name='fichapedagogica',
            name='listo_para_avanzar',
            field=models.BooleanField(default=False, help_text='True cuando completó Diario y Ficha de todas las semanas de su etapa actual.'),
        ),
    ]
