# Generated by Django 5.2.14 on 2026-09-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogia', '0007_ficha_listo_para_avanzar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaBienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarea de bienvenida',
                'verbose_name_plural': 'Tareas de bienvenida',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TareaBienvenidaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='pedagogia.tareabienvenida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_bienvenida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de tarea de bienvenida',
                'verbose_name_plural': 'Registros de tareas de bienvenida',
                'ordering': ['tarea__orden', 'tarea_id'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'tarea'), name='unique_usuario_tarea_bienvenida')],
            },
        ),
    ]
