# Generated by Django 5.2.14 on 2026-08-10 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoVista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto_en', models.DateTimeField(auto_now=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas', to='content.contenido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos_vistos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vista de contenido',
                'verbose_name_plural': 'Vistas de contenido',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'contenido'), name='unique_contenido_vista')],
            },
        ),
    ]
