import {
  BookMarked,
  BookOpen,
  Brain,
  CalendarCheck,
  Church,
  Circle,
  Flame,
  Gem,
  GraduationCap,
  HandHeart,
  Handshake,
  Heart,
  HeartHandshake,
  Lightbulb,
  Map,
  Moon,
  PersonStanding,
  Route,
  School,
  ScrollText,
  Smile,
  Sparkles,
  Sun,
  Sunrise,
  Sunset,
  Users,
  Wind,
  Wine,
} from 'lucide-react'

/** Catálogo de íconos disponibles para Praxis / Áreas (admin + miembro). */
export const LUCIDE_ICON_OPTIONS = [
  { value: 'Wine', label: 'Cáliz / Eucaristía' },
  { value: 'Church', label: 'Iglesia' },
  { value: 'Handshake', label: 'Reconciliación' },
  { value: 'Gem', label: 'Rosario' },
  { value: 'BookOpen', label: 'Libro abierto' },
  { value: 'BookMarked', label: 'Libro marcado' },
  { value: 'Sunrise', label: 'Amanecer' },
  { value: 'Sun', label: 'Sol' },
  { value: 'Sunset', label: 'Atardecer' },
  { value: 'Moon', label: 'Luna' },
  { value: 'HandHeart', label: 'Oración' },
  { value: 'Brain', label: 'Meditación' },
  { value: 'Sparkles', label: 'Adoración' },
  { value: 'Heart', label: 'Corazón' },
  { value: 'Flame', label: 'Llama' },
  { value: 'PersonStanding', label: 'Persona' },
  { value: 'Wind', label: 'Espíritu / viento' },
  { value: 'Smile', label: 'Ánimo' },
  { value: 'Users', label: 'Personas' },
  { value: 'GraduationCap', label: 'Formación' },
  { value: 'Lightbulb', label: 'Idea' },
  { value: 'ScrollText', label: 'Doctrina' },
  { value: 'School', label: 'Pedagogía' },
  { value: 'HeartHandshake', label: 'Acompañamiento' },
  { value: 'Map', label: 'Mapa / etapa' },
  { value: 'CalendarCheck', label: 'Calendario' },
  { value: 'Route', label: 'Camino' },
  { value: 'Circle', label: 'Círculo (genérico)' },
]

const ICON_MAP = {
  Wine,
  Church,
  Handshake,
  Gem,
  BookOpen,
  BookMarked,
  Sunrise,
  Sun,
  Sunset,
  Moon,
  HandHeart,
  Brain,
  Sparkles,
  Heart,
  Flame,
  PersonStanding,
  Wind,
  Smile,
  Users,
  GraduationCap,
  Lightbulb,
  ScrollText,
  School,
  HeartHandshake,
  Map,
  CalendarCheck,
  Route,
  Circle,
}

export function resolveLucideIcon(name) {
  return ICON_MAP[name] || Circle
}
